apiVersion: v1
kind: Pod
metadata:
  name: bastion-pod
spec:
  containers:
  - name: bastion-container
    image: vijayendraacr.azurecr.io/bastion:latest
    command: ["sleep", "infinity"] 

